newPlantsPerDay=5
initialNumberOfAnimals=5
energyPerPlant=5
lenOfGenome=5
mapVariant=GLOBE
mutationVariant=COMPLETE_RANDOMIZATION
behaviorVariant=COMPLETE_PREDESTINATION
plantGrowthVariant=FORESTED_EQUATOR
maxNumberOfMutations=5
mapHeight=5
initialEnergyOfAnimal=5
minNumberOfMutations=5
wellFedEnergy=5
initialNumberOfPlants=5
reproductionEnergy=5
mapWidth=5
